import os, json, datetime
from pathlib import Path
BASE = Path('courtdominion-automation')
today = datetime.date.today().isoformat()
out_dir = BASE / 'outputs' / 'generated' / today
out_dir.mkdir(parents=True, exist_ok=True)
# read projections if any
proj_file = out_dir / 'projections.json'
projections = None
if proj_file.exists():
    projections = json.load(open(proj_file))
# simple generator logic
platforms = ['twitter','reddit','discord','linkedin','email']
generated = {}
narrative = 'Injury fallout and waiver wire opportunities after last night\'s games.'
if projections:
    narrative += ' Top projection: ' + projections['players'][0]['name']
for p in platforms:
    text = f"{p.upper()} POST ({today})\n{narrative}\nKey takeaways:\n- Edge plays\n- Waiver pickups\n- Short term starts\n\nGenerated by GPT."
    fname = out_dir / f"{p}_draft.txt"
    with open(fname,'w') as f:
        f.write(text)
    generated[p] = str(fname)
# write rationale
rationale = {
    'date': today,
    'narrative': narrative,
    'why': 'High engagement topics based on injuries and waiver urgency',
    'choices': ['short waiver hooks','3 sleeper list','urgent start advice']
}
with open(out_dir / 'rationale.json','w') as rf:
    json.dump(rationale, rf)
# manifest
with open(out_dir / 'manifest.json','w') as mf:
    json.dump({'date': today, 'generated': generated}, mf)
print('Generated drafts and rationale at', out_dir)
