# auto-generated by generate_position_scarcity.py
# Do not edit manually — re-run the generator to update.

POSITION_SCARCITY = {
    'C': {
        'scarcity_multiplier': 1.2468,
        'avg_quality_players': 48.0,
        'avg_elite_players': 10.0,
        'avg_total_players': 82.0,
        'seasons_analyzed': 30,
    },
    'F': {
        'scarcity_multiplier': 0.9785,
        'avg_quality_players': 122.2,
        'avg_elite_players': 10.0,
        'avg_total_players': 188.3,
        'seasons_analyzed': 30,
    },
    'G': {
        'scarcity_multiplier': 0.8503,
        'avg_quality_players': 140.7,
        'avg_elite_players': 10.0,
        'avg_total_players': 206.1,
        'seasons_analyzed': 30,
    },
}
