# auto-generated by generate_sgp_weights.py
# Do not edit manually — re-run the generator to update.

SGP_WEIGHTS = {
    'category_weights': {
        'assists': 1.5281,
        'blocks': 1.9804,
        'points': 1.0,
        'rebounds': 1.0678,
        'steals': 0.9723,
        'three_pm': 1.8362,
    },
    'position_bonuses': {
        ('assists', 'C'): 1.79,
        ('assists', 'F'): 1.3677,
        ('blocks', 'G'): 2.0,
        ('points', 'C'): 1.0794,
        ('rebounds', 'G'): 1.4773,
        ('steals', 'C'): 1.3801,
        ('steals', 'F'): 1.0557,
        ('three_pm', 'C'): 2.0,
        ('three_pm', 'F'): 1.1404,
    },
    'seasons_analyzed': 30,
}
