#!/usr/bin/env python3
"""
Generate z-score baselines (league-wide mean/stddev per stat per position).

Feature 12: Standardized stat baselines for cross-category z-score comparison.

Produces:
    static_data/pricing/zscore_baselines.py

Usage:
    python -m data_collection.generate_zscore_baselines
"""

from pathlib import Path
from typing import Dict

import pandas as pd

from data_collection.utils import (
    STAT_COLUMNS,
    STATIC_DATA_DIR,
    load_all_seasons,
    rebucket_role,
)

QUALITY_ROLES = {"Starter", "Rotation"}

# Stats to compute baselines for (STAT_COLUMNS + fantasy_points)
BASELINE_STATS = list(STAT_COLUMNS) + ["fantasy_points"]


def compute_season_roles(df: pd.DataFrame) -> pd.DataFrame:
    """Compute season-average minutes per player-season, then re-bucket role."""
    season_avg = (
        df.groupby(["player_id", "season_start_year"])["minutes_played"]
        .mean()
        .reset_index()
        .rename(columns={"minutes_played": "season_avg_minutes"})
    )
    season_avg["rebucketed_role"] = season_avg["season_avg_minutes"].apply(rebucket_role)

    return df.merge(
        season_avg[["player_id", "season_start_year", "rebucketed_role"]],
        on=["player_id", "season_start_year"],
        how="left",
    )


def build_zscore_baselines(df: pd.DataFrame) -> Dict[str, dict]:
    """
    Compute mean and stddev for each stat, grouped by position + overall.

    Only includes Starter + Rotation players (fantasy-relevant pool).
    """
    quality = df[df["rebucketed_role"].isin(QUALITY_ROLES)]

    baselines = {}

    # Per position
    for pos, group in quality.groupby("position_group"):
        entry = {}
        for stat in BASELINE_STATS:
            entry[f"{stat}_mean"] = round(float(group[stat].mean()), 4)
            entry[f"{stat}_stddev"] = round(float(group[stat].std(ddof=1)), 4)
        entry["sample_size"] = len(group)
        baselines[pos] = entry

    # Overall (all positions combined)
    entry = {}
    for stat in BASELINE_STATS:
        entry[f"{stat}_mean"] = round(float(quality[stat].mean()), 4)
        entry[f"{stat}_stddev"] = round(float(quality[stat].std(ddof=1)), 4)
    entry["sample_size"] = len(quality)
    baselines["ALL"] = entry

    return baselines


def write_baselines_file(
    baselines: dict,
    variable_name: str,
    output_path: Path,
) -> None:
    """Write z-score baselines dict as a Python literal to a .py file."""
    lines = []
    lines.append("# auto-generated by generate_zscore_baselines.py")
    lines.append("# Do not edit manually — re-run the generator to update.")
    lines.append("")
    lines.append(f"{variable_name} = {{")

    for key in sorted(baselines.keys()):
        entry = baselines[key]
        lines.append(f"    '{key}': {{")

        for field in sorted(entry.keys()):
            lines.append(f"        '{field}': {entry[field]},")

        lines.append("    },")

    lines.append("}")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))


def main() -> None:
    """Generate z-score baselines."""
    print("Loading all seasons...")
    df = load_all_seasons()
    print(f"  Loaded {len(df):,} rows")

    # Standard cleanup
    before = len(df)
    df = df.dropna(subset=["age"])
    df["age"] = df["age"].astype(int)
    print(f"  Dropped {before - len(df):,} rows with null age ({len(df):,} remaining)")

    before = len(df)
    df = df.dropna(subset=["position_group"])
    print(
        f"  Dropped {before - len(df):,} rows with unknown position "
        f"({len(df):,} remaining)"
    )

    before = len(df)
    df = df[df["minutes_played"] > 0]
    print(
        f"  Dropped {before - len(df):,} rows with 0 minutes "
        f"({len(df):,} remaining)"
    )

    # Compute season-average roles
    print("Computing season-average roles...")
    df = compute_season_roles(df)

    # Calculate fantasy points
    df["fantasy_points"] = (
        df["points"] * 1.0
        + df["rebounds"] * 1.2
        + df["assists"] * 1.5
        + df["steals"] * 3.0
        + df["blocks"] * 3.0
        + df["turnovers"] * -1.0
    )

    # Filter to fantasy-relevant pool
    quality = df[df["rebucketed_role"].isin(QUALITY_ROLES)]
    print(f"  Fantasy-relevant pool (Starter+Rotation): {len(quality):,} games")

    # Build baselines
    print("Building z-score baselines...")
    baselines = build_zscore_baselines(df)

    for pos in sorted(baselines.keys()):
        entry = baselines[pos]
        print(
            f"  {pos}: pts_mean={entry['points_mean']:.1f}, "
            f"reb_mean={entry['rebounds_mean']:.1f}, "
            f"ast_mean={entry['assists_mean']:.1f}, "
            f"n={entry['sample_size']:,}"
        )

    # Write output
    output_path = STATIC_DATA_DIR / "pricing" / "zscore_baselines.py"
    write_baselines_file(baselines, "ZSCORE_BASELINES", output_path)
    print(f"  Written: {output_path}")

    print("\nDone.")


if __name__ == "__main__":
    main()
