#!/usr/bin/env python3
"""
Generate durability (games played) profiles from 30 years of NBA game logs.

Feature 11: Expected games played per season by age/position/role.

Produces:
    static_data/durability/durability_profiles.py

Usage:
    python -m data_collection.generate_durability_profiles
"""

from pathlib import Path
from typing import Dict, Tuple

import pandas as pd

from data_collection.utils import (
    STATIC_DATA_DIR,
    load_all_seasons,
    rebucket_role,
)

MIN_SAMPLE_SIZE = 50

DURABILITY_FIELDS = [
    "avg_games_played",
    "stddev_games_played",
    "durability_score",
    "ironman_pct",
    "sample_size",
]


def aggregate_player_seasons(df: pd.DataFrame) -> pd.DataFrame:
    """
    Collapse game rows into player-season summaries.

    For each (player_id, season_start_year):
      - games_played: count of rows
      - season_age: mode of age column
      - position_group: mode of position_group column
      - season_avg_minutes: mean of minutes_played

    Then applies rebucket_role to season_avg_minutes.
    """
    agg = (
        df.groupby(["player_id", "season_start_year"])
        .agg(
            games_played=("game_date", "count"),
            season_age=("age", lambda x: x.mode().iloc[0]),
            position_group=("position_group", lambda x: x.mode().iloc[0]),
            season_avg_minutes=("minutes_played", "mean"),
        )
        .reset_index()
    )

    agg["rebucketed_role"] = agg["season_avg_minutes"].apply(rebucket_role)
    return agg


def build_durability_profiles(
    player_seasons: pd.DataFrame,
    min_sample: int = MIN_SAMPLE_SIZE,
) -> Dict[Tuple[int, str, str], dict]:
    """
    Group player-seasons by (season_age, position_group, rebucketed_role)
    and compute durability statistics.
    """
    grouped = player_seasons.groupby(
        ["season_age", "position_group", "rebucketed_role"]
    )

    profiles = {}
    for (age, pos, role), group in grouped:
        if len(group) < min_sample:
            continue

        gp = group["games_played"]
        avg_gp = round(float(gp.mean()), 4)

        entry = {
            "avg_games_played": avg_gp,
            "stddev_games_played": round(float(gp.std(ddof=1)), 4),
            "durability_score": round(avg_gp / 82, 4),
            "ironman_pct": round(float((gp >= 70).mean()), 4),
            "sample_size": len(group),
        }

        profiles[(int(age), pos, role)] = entry

    return profiles


def write_profiles_file(
    profiles: dict,
    variable_name: str,
    output_path: Path,
) -> None:
    """Write durability dict as a Python literal to a .py file."""
    lines = []
    lines.append("# auto-generated by generate_durability_profiles.py")
    lines.append("# Do not edit manually — re-run the generator to update.")
    lines.append("")
    lines.append(f"{variable_name} = {{")

    for key in sorted(profiles.keys()):
        entry = profiles[key]
        age, pos, role = key
        lines.append(f"    ({age}, '{pos}', '{role}'): {{")

        for field in DURABILITY_FIELDS:
            lines.append(f"        '{field}': {entry[field]},")

        lines.append("    },")

    lines.append("}")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))


def main() -> None:
    """Generate durability profiles."""
    print("Loading all seasons...")
    df = load_all_seasons()
    print(f"  Loaded {len(df):,} rows")

    # Drop null age, cast to int
    before = len(df)
    df = df.dropna(subset=["age"])
    df["age"] = df["age"].astype(int)
    print(f"  Dropped {before - len(df):,} rows with null age ({len(df):,} remaining)")

    # Drop null position_group
    before = len(df)
    df = df.dropna(subset=["position_group"])
    print(
        f"  Dropped {before - len(df):,} rows with unknown position "
        f"({len(df):,} remaining)"
    )

    # NOTE: We do NOT drop 0-minute rows — a CSV row = a game appearance

    # Aggregate to player-seasons
    print("Aggregating to player-seasons...")
    player_seasons = aggregate_player_seasons(df)
    print(f"  Player-seasons: {len(player_seasons):,}")

    # Build durability profiles
    print("Building durability profiles...")
    profiles = build_durability_profiles(player_seasons)
    print(f"  Buckets: {len(profiles)} (after min sample filter)")

    # Write output
    output_path = STATIC_DATA_DIR / "durability" / "durability_profiles.py"
    write_profiles_file(profiles, "DURABILITY_PROFILES", output_path)
    print(f"  Written: {output_path}")

    print("\nDone.")


if __name__ == "__main__":
    main()
