#!/usr/bin/env python3
"""
Generate ceiling game (blowup probability) profiles from 30 years of NBA game logs.

Feature 10: Probability and magnitude of 90th-percentile performances.

Produces:
    static_data/profiles/ceiling_profiles.py

Usage:
    python -m data_collection.generate_ceiling_profiles
"""

from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import pandas as pd

from data_collection.utils import (
    STATIC_DATA_DIR,
    load_all_seasons,
    rebucket_role,
)

MIN_SAMPLE_SIZE = 50

CEILING_FIELDS = [
    "ceiling_threshold",
    "ceiling_game_pct",
    "avg_ceiling_game_pts",
    "avg_fantasy_pts",
    "sample_size",
]


def compute_season_roles(df: pd.DataFrame) -> pd.DataFrame:
    """Compute season-average minutes per player-season, then re-bucket role."""
    season_avg = (
        df.groupby(["player_id", "season_start_year"])["minutes_played"]
        .mean()
        .reset_index()
        .rename(columns={"minutes_played": "season_avg_minutes"})
    )
    season_avg["rebucketed_role"] = season_avg["season_avg_minutes"].apply(rebucket_role)

    return df.merge(
        season_avg[["player_id", "season_start_year", "rebucketed_role"]],
        on=["player_id", "season_start_year"],
        how="left",
    )


def build_ceiling_profiles(
    df: pd.DataFrame,
    min_sample: int = MIN_SAMPLE_SIZE,
) -> Dict[Tuple[int, str, str], dict]:
    """
    Group games by (age, position_group, rebucketed_role) and compute
    ceiling game statistics using 90th percentile threshold.
    """
    grouped = df.groupby(["age", "position_group", "rebucketed_role"])

    profiles = {}
    for (age, pos, role), group in grouped:
        if len(group) < min_sample:
            continue

        fp = group["fantasy_points"]
        threshold = float(np.percentile(fp, 90))
        ceiling_games = fp[fp >= threshold]

        entry = {
            "ceiling_threshold": round(threshold, 4),
            "ceiling_game_pct": round(float(len(ceiling_games) / len(fp)), 4),
            "avg_ceiling_game_pts": round(float(ceiling_games.mean()), 4),
            "avg_fantasy_pts": round(float(fp.mean()), 4),
            "sample_size": len(group),
        }

        profiles[(int(age), pos, role)] = entry

    return profiles


def write_profiles_file(
    profiles: dict,
    variable_name: str,
    output_path: Path,
) -> None:
    """Write ceiling profiles dict as a Python literal to a .py file."""
    lines = []
    lines.append("# auto-generated by generate_ceiling_profiles.py")
    lines.append("# Do not edit manually — re-run the generator to update.")
    lines.append("")
    lines.append(f"{variable_name} = {{")

    for key in sorted(profiles.keys()):
        entry = profiles[key]
        age, pos, role = key
        lines.append(f"    ({age}, '{pos}', '{role}'): {{")

        for field in CEILING_FIELDS:
            lines.append(f"        '{field}': {entry[field]},")

        lines.append("    },")

    lines.append("}")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))


def main() -> None:
    """Generate ceiling game profiles."""
    print("Loading all seasons...")
    df = load_all_seasons()
    print(f"  Loaded {len(df):,} rows")

    # Standard cleanup
    before = len(df)
    df = df.dropna(subset=["age"])
    df["age"] = df["age"].astype(int)
    print(f"  Dropped {before - len(df):,} rows with null age ({len(df):,} remaining)")

    before = len(df)
    df = df.dropna(subset=["position_group"])
    print(
        f"  Dropped {before - len(df):,} rows with unknown position "
        f"({len(df):,} remaining)"
    )

    before = len(df)
    df = df[df["minutes_played"] > 0]
    print(
        f"  Dropped {before - len(df):,} rows with 0 minutes "
        f"({len(df):,} remaining)"
    )

    # Compute season-average roles
    print("Computing season-average roles...")
    df = compute_season_roles(df)

    # Calculate fantasy points
    print("Calculating fantasy points...")
    df["fantasy_points"] = (
        df["points"] * 1.0
        + df["rebounds"] * 1.2
        + df["assists"] * 1.5
        + df["steals"] * 3.0
        + df["blocks"] * 3.0
        + df["turnovers"] * -1.0
    )

    # Build ceiling profiles
    print("Building ceiling profiles...")
    profiles = build_ceiling_profiles(df)
    print(f"  Buckets: {len(profiles)} (after min sample filter)")

    # Write output
    output_path = STATIC_DATA_DIR / "profiles" / "ceiling_profiles.py"
    write_profiles_file(profiles, "CEILING_PROFILES", output_path)
    print(f"  Written: {output_path}")

    print("\nDone.")


if __name__ == "__main__":
    main()
